defaults:
  - model: qwen
  - _self_

experiment:
  task: "mnli"
  ood_task: "rte"
  batch_size: 16
  learning_rate: 2e-4
  num_epochs: 2
  swag_start_epoch: 1
  swag_collect_freq: 1
  swag_scale: 1.0
  max_num_models: 20
  seed: 42
  save_path: "./outputs"
  max_length: 128
  dataset_percentage: 0.2
