experiment:
  seed: 42
  task: "trivia_qa"
  subset: "rc.nocontext"
  num_epochs: 3
  learning_rate: 4e-4
  batch_size: 32
  max_length: 128
  dataset_percentage: 0.05
  swag_start_ratio: 0.75
  swag_total_samples: 30
  max_num_models: 20
  swag_scale: 2.0
  swag_eval_samples: 15
  swag_lr_ratio: 1.0
  save_path: "outputs_qa"
  max_new_tokens: 32

model:
  model_name: "Qwen/Qwen3-0.6B"
  lora_r: 16
  lora_alpha: 32
  lora_dropout: 0.1
  target_modules: ["q_proj", "v_proj", "k_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]
